In [1]:
#CREATING SIMPLE ARRAYS....
import numpy as np
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [2]:
a.shape

(3, 5)

In [3]:
a.ndim

2

In [6]:
a.dtype.name

'int32'

In [11]:
a.itemsize

4

In [10]:
a.size

15

In [12]:
type(a)

numpy.ndarray

In [13]:
b = np.array([6, 7, 8])
b

array([6, 7, 8])

In [14]:
type(b)

numpy.ndarray

In [15]:
b.dtype

dtype('int32')

In [16]:
b = np.array([1.2, 3.5, 5.1])
b.dtype

dtype('float64')

In [17]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
c = np.array( [ [1,2], [3,4] ], dtype=complex )
c

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j]])

In [19]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [20]:
np.ones( (2,3,4), dtype=np.int16 ) 

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

In [21]:
np.empty( (2,3) )

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [22]:
np.arange( 10, 30, 5 )

array([10, 15, 20, 25])

In [23]:
np.arange( 0, 2, 0.3 )

array([0. , 0.3, 0.6, 0.9, 1.2, 1.5, 1.8])

In [25]:
# 1d array
a = np.arange(6)                        
print('1d array\n',a)

# 2d array
b = np.arange(12).reshape(4,3)        
print('2d array\n',b)

# 3d array
c = np.arange(24).reshape(2,3,4)         
print('3d array\n',c)

1d array
 [0 1 2 3 4 5]
2d array
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
3d array
 [[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [26]:
print(np.arange(10000))

[   0    1    2 ... 9997 9998 9999]
